### ISSUE TITLE
How to distribute blosc?

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-cmd#3]
@k-dominik could we distribute blosc via conda?

See here: https://imagesc.zulipchat.com/#narrow/stream/327237-SciJava/topic/Blosc.20in.20Maven

**Comment by k-dominik** [comment]
Sure I assume there is some ABI stability :) - we could add it to the requirements in the feedstock repo. But first I'd try it locally if I were you (as @ctrueden suggested on Zulip).

**Comment by tischi** [comment]
@k-dominik this works:

`mamba install -c conda-forge blosc`

can you help with adding it to the feedstock repo?
